### ISSUE TITLE
null value in column "time" violates not-null constraint

### ISSUE THREAD

**Issue by Zitrax** [jensl/critic#102]
Got:

```
Extension failure: returned 1
Failed to call 'ready.js::is_ready()':
  PostgreSQL.Error: ERROR:  null value in column "time" violates not-null constraint
DETAIL:  Failing row contains (3, 3, 9, 1, null, current, Test, null).

    <program code> at <Library>/critic-batch.js:343
```
when trying to use writeNote(string text) in NewBatch.

Worked after: `alter table comments alter time set default now();`

Does it make sense to add the default to dbschema.comments.sql ?

**Comment by jensl** [comment]
Yes, it's seems an obvious omission that the comments.time column doesn't have a default. All the other timestamp columns default to now(), after all.

The Critic instance here at Opera does have a default for that column, so I have obviously noticed the problem myself at some point (probably years ago) but only fixed it by altering the column in the database, and not patching the db schema script.

**Comment by jensl** [comment]
Fixed in https://github.com/jensl/critic/commit/7398a694. Thanks for reporting!
