### ISSUE TITLE
Trigger tracked branch update

### ISSUE THREAD

**Issue by Zitrax** [jensl/critic#121]
By default the tracked branches are scheduled to update once per day and I can reduce this in the database. or manually click the "Update now" button as admin.

But I would prefer if the branch could be always in sync, however pushing directly to it gives:

    remote: The branch 'master' is set up to track 'master' in
    remote:   <repo_url>
    remote: Please don't push it manually to this repository.

is there an alternative or preferred way to trigger the update 'now' so I could set up a git hook to tell critic to update the branch?

**Comment by jensl** [comment]
Using this extension is the recommended approach, I suppose: https://github.com/jensl/UpdateTrackedBranch

**Comment by Zitrax** [comment]
Nice, sounds what I was looking for. Thanks, I'll try it.
